version: '2.9'

services:
  db:
    image: mysql:latest
    container_name: local_mysql
    environment:
      MYSQL_DATABASE: stats
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mysql_network

volumes:
  db_data:

networks:
  mysql_network:
    driver: bridge